// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_1.Models;

#nullable disable

namespace Project_1.Migrations
{
    [DbContext(typeof(MarketReadySiteContext))]
    [Migration("20251028052701_newServer_migrate")]
    partial class newServer_migrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project_1.Models.AboutTbl", b =>
                {
                    b.Property<int>("AboutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("about_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AboutId"));

                    b.Property<string>("AboutBtnText")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .HasColumnName("about_btn_text")
                        .IsFixedLength();

                    b.Property<string>("AboutDesc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("about_desc");

                    b.Property<string>("AboutTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .HasColumnName("about_title")
                        .IsFixedLength();

                    b.HasKey("AboutId");

                    b.ToTable("about_tbl", (string)null);
                });

            modelBuilder.Entity("Project_1.Models.AdminTable", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("admin_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("AdminEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .HasColumnName("admin_email")
                        .IsFixedLength();

                    b.Property<string>("AdminName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .HasColumnName("admin_name")
                        .IsFixedLength();

                    b.Property<string>("AdminPassword")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nchar(255)")
                        .HasColumnName("admin_password")
                        .IsFixedLength();

                    b.Property<string>("AdminPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nchar(15)")
                        .HasColumnName("admin_phone")
                        .IsFixedLength();

                    b.HasKey("AdminId");

                    b.ToTable("admin_table", (string)null);
                });

            modelBuilder.Entity("Project_1.Models.BookingTbl", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("book_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<DateTime?>("BookerBookingDate")
                        .HasColumnType("datetime")
                        .HasColumnName("booker_booking_date");

                    b.Property<string>("BookerEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .HasColumnName("booker_email")
                        .IsFixedLength();

                    b.Property<string>("BookerName")
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .HasColumnName("booker_name")
                        .IsFixedLength();

                    b.Property<string>("BookerPhone")
                        .HasMaxLength(15)
                        .HasColumnType("nchar(15)")
                        .HasColumnName("booker_phone")
                        .IsFixedLength();

                    b.Property<int?>("BookerTotalPersons")
                        .HasColumnType("int")
                        .HasColumnName("booker_total_persons");

                    b.HasKey("BookId");

                    b.ToTable("booking_tbl", (string)null);
                });

            modelBuilder.Entity("Project_1.Models.HomeTbl", b =>
                {
                    b.Property<int>("HomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("home_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HomeId"));

                    b.Property<string>("HomeBgImg")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("home_bg_img");

                    b.Property<string>("HomeDesc")
                        .HasColumnType("text")
                        .HasColumnName("home_desc");

                    b.Property<string>("HomeTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .HasColumnName("home_title")
                        .IsFixedLength();

                    b.HasKey("HomeId");

                    b.ToTable("home_tbl", (string)null);
                });

            modelBuilder.Entity("Project_1.Models.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("menu_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuId"));

                    b.Property<int?>("Item1Price")
                        .HasColumnType("int")
                        .HasColumnName("item_1_price");

                    b.Property<int?>("Item2Price")
                        .HasColumnType("int")
                        .HasColumnName("item_2_price");

                    b.Property<int?>("Item3Price")
                        .HasColumnType("int")
                        .HasColumnName("item_3_price");

                    b.Property<int?>("Item4Price")
                        .HasColumnType("int")
                        .HasColumnName("item_4_price");

                    b.Property<int?>("Item5Price")
                        .HasColumnType("int")
                        .HasColumnName("item_5_price");

                    b.Property<int?>("Item6Price")
                        .HasColumnType("int")
                        .HasColumnName("item_6_price");

                    b.Property<int?>("Item7Price")
                        .HasColumnType("int")
                        .HasColumnName("item_7_price");

                    b.Property<int?>("Item8Price")
                        .HasColumnType("int")
                        .HasColumnName("item_8_price");

                    b.Property<int?>("Item9Price")
                        .HasColumnType("int")
                        .HasColumnName("item_9_price");

                    b.Property<string>("ItemDesc1")
                        .HasColumnType("text")
                        .HasColumnName("item_desc_1");

                    b.Property<string>("ItemDesc2")
                        .HasColumnType("text")
                        .HasColumnName("item_desc_2");

                    b.Property<string>("ItemDesc3")
                        .HasColumnType("text")
                        .HasColumnName("item_desc_3");

                    b.Property<string>("ItemDesc4")
                        .HasColumnType("text")
                        .HasColumnName("item_desc_4");

                    b.Property<string>("ItemDesc5")
                        .HasColumnType("text")
                        .HasColumnName("item_desc_5");

                    b.Property<string>("ItemDesc6")
                        .HasColumnType("text")
                        .HasColumnName("item_desc_6");

                    b.Property<string>("ItemDesc7")
                        .HasColumnType("text")
                        .HasColumnName("item_desc_7");

                    b.Property<string>("ItemDesc8")
                        .HasColumnType("text")
                        .HasColumnName("item_desc_8");

                    b.Property<string>("ItemDesc9")
                        .HasColumnType("text")
                        .HasColumnName("item_desc_9");

                    b.Property<string>("ItemImg1")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("item_img_1")
                        .IsFixedLength();

                    b.Property<string>("ItemImg2")
                        .HasColumnType("text")
                        .HasColumnName("item_img_2");

                    b.Property<string>("ItemImg3")
                        .HasColumnType("text")
                        .HasColumnName("item_img_3");

                    b.Property<string>("ItemImg4")
                        .HasColumnType("text")
                        .HasColumnName("item_img_4");

                    b.Property<string>("ItemImg5")
                        .HasColumnType("text")
                        .HasColumnName("item_img_5");

                    b.Property<string>("ItemImg6")
                        .HasColumnType("text")
                        .HasColumnName("item_img_6");

                    b.Property<string>("ItemImg7")
                        .HasColumnType("text")
                        .HasColumnName("item_img_7");

                    b.Property<string>("ItemImg8")
                        .HasColumnType("text")
                        .HasColumnName("item_img_8");

                    b.Property<string>("ItemImg9")
                        .HasColumnType("text")
                        .HasColumnName("item_img_9");

                    b.Property<string>("ItemTitle1")
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .HasColumnName("item_title_1")
                        .IsFixedLength();

                    b.Property<string>("ItemTitle2")
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .HasColumnName("item_title_2")
                        .IsFixedLength();

                    b.Property<string>("ItemTitle3")
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .HasColumnName("item_title_3")
                        .IsFixedLength();

                    b.Property<string>("ItemTitle4")
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .HasColumnName("item_title_4")
                        .IsFixedLength();

                    b.Property<string>("ItemTitle5")
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .HasColumnName("item_title_5")
                        .IsFixedLength();

                    b.Property<string>("ItemTitle6")
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .HasColumnName("item_title_6")
                        .IsFixedLength();

                    b.Property<string>("ItemTitle7")
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .HasColumnName("item_title_7")
                        .IsFixedLength();

                    b.Property<string>("ItemTitle8")
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .HasColumnName("item_title_8")
                        .IsFixedLength();

                    b.Property<string>("ItemTitle9")
                        .HasMaxLength(100)
                        .HasColumnType("nchar(100)")
                        .HasColumnName("item_title_9")
                        .IsFixedLength();

                    b.HasKey("MenuId");

                    b.ToTable("menu", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
